-- 12/ Q1
CREATE TABLE EMP_HW (
    EMPNO       NUMBER( 4 ),
    ENAME       VARCHAR( 10 ),
    JOB         VARCHAR( 9 ),
    MGR         NUMBER( 4 ),
    HIREDATE    DATE,
    SAL         NUMBER ( 7, 2 ),
    COMM        NUMBER ( 7, 2 ),
    DEPTNO      NUMBER ( 2 ));   
    
DESC EMP_HW;

-- 12/ Q2
ALTER TABLE EMP_HW
    ADD BIGO    VARCHAR( 20 );

DESC EMP_HW;


-- 12/ Q3
ALTER TABLE EMP_HW
    MODIFY BIGO VARCHAR( 30 );
    
DESC EMP_HW;


-- 12/ Q4
ALTER TABLE EMP_HW
    RENAME COLUMN BIGO TO REMARK;
    
SELECT * FROM EMP_HW;


-- 12/ Q5
SELECT * FROM EMP;

INSERT INTO EMP_HW
    SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO, NULL
    FROM EMP;

SELECT * FROM EMP_HW;

-- 12/ Q6
DROP TABLE EMP_HW;