CREATE SYNONYM E
    FOR EMP;

-- 13/ Q1

DROP TABLE EMPIDX;

CREATE TABLE EMPIDX
    AS SELECT *
    FROM E;  

SELECT * FROM EMPIDX;

CREATE INDEX IDX_EMPIDX_EMPNO
    ON EMPIDX ( EMPNO );
    
SELECT * FROM USER_INDEXES;
SELECT * FROM USER_IND_COLUMNS;


-- 13/ Q2

DROP VIEW EMPIDX_OVER15K;

CREATE OR REPLACE VIEW EMPIDX_OVER15K
        AS ( SELECT EMPNO,
                    ENAME,
                    JOB,
                    DEPTNO,
                    SAL,
                    NVL2( COMM, 'O', 'X' ) AS COMM
                FROM EMPIDX
                WHERE SAL > 1500 );
                
SELECT * FROM EMPIDX_OVER15K;



-- 13/ Q3

DROP TABLE DEPTSEQ;

CREATE TABLE DEPTSEQ
    AS SELECT *
    FROM DEPT;
   
    
SELECT * FROM DEPTSEQ;

CREATE SEQUENCE S_DEPTSEQ
    INCREMENT BY 1
    START WITH 1
    MAXVALUE 99
    MINVALUE 1
    NOCYCLE
    NOCACHE;
    
SELECT * FROM USER_SEQUENCES;    

INSERT INTO DEPTSEQ ( DEPTNO, DNAME, LOC ) 
    VALUES ( S_DEPTSEQ.NEXTVAL, 'DATABASE', 'SEOUL' );
    
INSERT INTO DEPTSEQ ( DEPTNO, DNAME, LOC ) 
    VALUES ( S_DEPTSEQ.NEXTVAL, 'WEB', 'BUSAN' );
    
INSERT INTO DEPTSEQ ( DEPTNO, DNAME, LOC ) 
    VALUES ( S_DEPTSEQ.NEXTVAL, 'MOBILE', 'ILSAN' );
    
SELECT * FROM DEPTSEQ;

SELECT S_DEPTSEQ.CURRVAL FROM DUAL;


SELECT * FROM USER_VIEWs;
SELECT * FROM USER_INDEXES;
SELECT * FROM USER_TABLES;