--14/ Q1-1
CREATE TABLE DEPT_CONST(
    DEPTNO      NUMBER( 2 ),
    DNAME       VARCHAR2( 14 ),
    LOC         VARCHAR2( 13 ) CONSTRAINT DEPTCONST_LOC_NN NOT NULL,
    CONSTRAINT DEPTCONST_DEPTNO_PK PRIMARY KEY( DEPTNO ),
    CONSTRAINT DEPTCONST_DNAME_UNQ UNIQUE( DNAME ));
¤·
DESC DEPT_CONST;
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'DEPT_CONST'; 

-- Q1-2
CREATE TABLE EMP_CONST (
    EMPNO       NUMBER( 4 ) CONSTRAINT EMPCONST_EMPNO_PK PRIMARY KEY ,
    ENAME       VARCHAR2( 10 ) CONSTRAINT EMPCONST_ENAME_NN NOT NULL,
    JOB         VARCHAR2( 9 ),
    TEL         VARCHAR( 20 ) CONSTRAINT EMPCONST_TEL_UNQ UNIQUE,
    HIREDATE    DATE,
    SAL         NUMBER( 7, 2 ) CONSTRAINT EMPCONST_SAL_CHK CHECK( SAL BETWEEN 1000 AND 9999 ),
    COMM        NUMBER( 7, 2 ),
    DEPTNO      NUMBER( 2 ) CONSTRAINT EMPCONST_DEPTNO_FK REFERENCES DEPT_CONST( DEPTNO ));
    
DESC EMP_CONST;
SELECT TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE
    FROM USER_CONSTRAINTS WHERE TABLE_NAME IN ( 'DEPT_CONST', 'EMP_CONST' )
    ORDER BY CONSTRAINT_NAME;


-- Çü½Ä 2
CREATE TABLE EMP_CONST2 (
    EMPNO       NUMBER( 4 ), --CONSTRAINT EMPCONST_EMPNO_PK PRIMARY KEY ,
    ENAME       VARCHAR2( 10 ) CONSTRAINT EMPCONST_ENAME_NN2 NOT NULL,
    JOB         VARCHAR2( 9 ),
    TEL         VARCHAR( 20 ), --CONSTRAINT EMPCONST_TEL_UNQ UNIQUE,
    HIREDATE    DATE,
    SAL         NUMBER( 7 ), --CONSTRAINT EMPCONST_SAL_CHK CHECK( SAL BETWEEN 1000 AND 9999 ),
    COMM        NUMBER( 7 ),
    DEPTNO      NUMBER( 2 ), --CONSTRAINT EMPCONST_DEPTNO_FK REFERENCES DEPT_CONST( DEPTNO ),
    
        CONSTRAINT EMPCONST_EMPNO_PK2 PRIMARY KEY( EMPNO ),
        CONSTRAINT EMPCONST_TEL_UNQ2 UNIQUE( TEL ),
        CONSTRAINT EMPCONST_SAL_CHK2 CHECK( SAL BETWEEN 1000 AND 9999 ),
        CONSTRAINT EMPCONST_DEPTNO_FK2 FOREIGN KEY( DEPTNO )
            REFERENCES DEPT_CONST( DEPTNO ));
    
DESC EMP_CONST2;
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'EMP_CONST2'; 