-- 15/ Q1

    -- SYSTEM 계정으로
    CREATE USER PREV_HW
    IDENTIFIED BY ORCL;

    GRANT CREATE SESSION TO PREV_HW;


-- 15/ Q2

    -- SCOTT 계정으로
    GRANT SELECT ON EMP TO PREV_HW;
    GRANT SELECT ON DEPT TO PREV_HW;
    GRANT SELECT ON SALGRADE TO PREV_HW;
    
    
    -- PREV_HW 계정으로
    SELECT * FROM SCOTT.EMP;
    SELECT * FROM SCOTT.DEPT;
    SELECT * FROM SCOTT.SALGRADE;
    


-- 15/ Q3

    -- SCOTT 계정으로
    REVOKE SELECT ON SALGRADE FROM PREV_HW;
    
    
    -- PREV_HW 계정으로
    SELECT * FROM SCOTT.EMP;
    SELECT * FROM SCOTT.DEPT;
    SELECT * FROM SCOTT.SALGRADE;
    
    

DROP USER PREV_HW;