--16 /Q1
SET SERVEROUTPUT ON;

BEGIN
    FOR I IN 0..10 LOOP
        CONTINUE WHEN MOD( i, 2 ) = 0;
        DBMS_OUTPUT.PUT_LINE( '현재 i의 값:' || i );
    END LOOP;
END;
/


--16 /Q2

SELECT * FROM DEPT;

DECLARE 
    V_DEPTNO DEPT.DEPTNO%TYPE  := 40;
BEGIN
    IF V_DEPTNO = 10 THEN
        DBMS_OUTPUT.PUT_LINE( 'DNAME: ACCOUNTING'  );
    ELSIF V_DEPTNO = 20 THEN
        DBMS_OUTPUT.PUT_LINE( 'DNAME: RESEARCH'  );
    ELSIF V_DEPTNO = 30 THEN
        DBMS_OUTPUT.PUT_LINE( 'DNAME: SALES'  );
    ELSIF V_DEPTNO = 40 THEN
        DBMS_OUTPUT.PUT_LINE( 'DNAME: OPERATIONS'  );
    ELSE
        DBMS_OUTPUT.PUT_LINE( 'DNAME: ' || 'N/A' );
    END IF;
END;
/

DECLARE V_DEPTNO DEPT.DEPTNO%TYPE := 3;

BEGIN
    CASE
        WHEN V_DEPTNO = 10 THEN 
            DBMS_OUTPUT.PUT_LINE( 'DNAME: ACCOUNTING'  );
        WHEN V_DEPTNO = 20 THEN 
            DBMS_OUTPUT.PUT_LINE( 'DNAME: RESEARCH'  );
        WHEN V_DEPTNO = 30 THEN 
            DBMS_OUTPUT.PUT_LINE( 'DNAME: SALES'  );
        WHEN V_DEPTNO = 40 THEN 
            DBMS_OUTPUT.PUT_LINE( 'DNAME: OPERATIONS'  );
        ELSE 
            DBMS_OUTPUT.PUT_LINE( 'DNAME: N/A' );
    END CASE;
END;
/


 
    