-- 7/ Q1
SELECT * FROM EMP;

SELECT DEPTNO,
    TRUNC (AVG(SAL))AS AVG_SAL,
    MAX( SAL ) AS MAX_SAL,
    MIN( SAL ) AS MIN_SAL,
    COUNT(*) AS CNT
FROM EMP
GROUP BY DEPTNO;


-- 7/ Q2
SELECT * FROM EMP;

SELECT JOB, COUNT(*)
    FROM EMP
    GROUP BY JOB
    HAVING COUNT(*) >= 3;
    
    
-- 7/ Q3
SELECT * FROM EMP;

SELECT LPAD( SUBSTR( HIREDATE, 1,2), 4, '19' ) AS HIRE_YEAR, DEPTNO, COUNT(*) AS CNT
    FROM EMP
    GROUP BY LPAD( SUBSTR( HIREDATE, 1,2), 4, '19' ), DEPTNO;
    
    
-- 7/ Q4
SELECT COMM FROM EMP;

SELECT NVL2( COMM, 'O', 'X' ) AS EXIST_COMM,
    COUNT(*) AS CNT
FROM EMP
GROUP BY NVL2( COMM, 'O', 'X' );

-- 7/ Q5
SELECT * FROM EMP;

SELECT DEPTNO, 
    LPAD( SUBSTR( HIREDATE, 1,2), 4, '19' ) AS HIRE_YEAR, 
    COUNT(*) AS CNT,
    MAX( SAL ) AS MAX_SAL,
    SUM( SAL ) AS SUM_SAL,
    TRUNC(AVG( SAL )) AS AVG_SAL
FROM EMP
    GROUP BY ROLLUP ( DEPTNO, LPAD( SUBSTR( HIREDATE, 1,2), 4, '19' ));