--DROP TABLE
CREATE TABLE EMP_DDL (
    EMPNO       NUMBER( 4 ),
    ENAME       VARCHAR2( 10 ),
    JOB         VARCHAR2( 9 ),
    MGR         NUMBER( 4 ),
    HIREDATE    DATE,
    SAL         NUMBER( 7,2 ),
    COMM        NUMBER( 7,2 ),
    DEPTNO      NUMBER( 2 ));
    
SELECT * FROM EMP_DDL;
DESC EMP_DDl;


CREATE TABLE DEPT_DDL
    AS SELECT * FROM DEPT;
    
SELECT * FROM DEPT_DDL;
DESC DEPT_DDL;
DESC DEPT;

-- 사원 번호( DEPTNO ) 가 30인 데이터만 가져와서 테이블 생성
CREATE TABLE EMP_DDL_30
    AS SELECT * FROM EMP
    WHERE DEPTNO = 30;
    
SELECT * FROM EMP_DDL_30;

-- WHERE 1 <> 1; 조건 이용해서 데이터 값 X, 형식만 가져오기
CREATE TABLE EMP_DDL_01
    AS SELECT * FROM EMP
    WHERE 1 <> 1;
    
SELECT * FROM EMP_DDL_01;

-- JOIN
CREATE TABLE EMPDEPT_01
    AS SELECT E.EMPNO, E.ENAMe, E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM, D.DEPTNO, D.DNAME, D.LOC FROM EMP E, DEPT D
    WHERE 1 <> 1;
    
SELECT * FROM EMPDEPT_01;

-- ALTER로 테이블 변경
CREATE TABLE EMP_ALTER
    AS SELECT * FROM EMP;

SELECT * FROM EMP_ALTER;

-- ADD
ALTER TABLE EMP_ALTER
    ADD HP VARCHAR( 20 );
    
SELECT * FROM EMP_ALTER;

-- RENAME 
ALTER TABLE EMP_ALTER
RENAME COLUMN HP TO TEL;

SELECT * FROM EMP_ALTER;

-- MODIFY
ALTER TABLE EMP_ALTER
MODIFY EMPNO NUMBER ( 4 );

DESC EMP_ALTER;

-- DROP
ALTER TABLE EMP_ALTER
DROP COLUMN TEL;

SELECT * FROM EMP_ALTER;

RENAME EMP_ALTER TO EMP_RENAME;

SELECT * FROM EMP_RENAME;

TRUNCATE TABLE EMP_RENAME;

DROP TABLE CHAP10HW_DEPT;
