CREATE USER SALES
IDENTIFIED BY SALES;

SELECT * FROM DBA_USERS;

GRANT RESOURCE, CREATE SESSION, CREATE TABLE TO SALES;

CREATE ROLE SALESROLE;

GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE SYNONYM, CREATE SESSION, CREATE TABLE 
    TO SALESROLE;
    
    
GRANT SALESROLE TO SALES;

SELECT * FROM DBA_ROLE_privs WHERE GRANTEE = 'SALESROLE';