-- 객체 종류

SELECT * FROM DICT;


-- USER

SELECT * FROM USER_TABLES; -- SCOTT의 모든 테이블

-- ALL

SELECT * FROM ALL_TABLES; -- SCOTT 계정에 권한이 허용된 모든 테이블

-- DBA ( DB 관리 권한 )

SELECT * FROM DBA_TABLES;

-- INDEX

SELECT * FROM USER_INDEXES;
SELECT * FROM USER_IND_COLUMNS;


-- 인덱스 생성

CREATE INDEX IDX_EMP_SAL
    ON EMP(SAL);
    
-- 인덱스 삭제

DROP INDEX IDX_EMP_SAL;

-- 뷰 생성 ( SYSTEM 권한 필요 )

SELECT * FROM USER_TABLES;
SELECT * FROM USRE_VIEWS;

--
CREATE VIEW VW_EMP20
    AS( SELECT EMPNO, ENAME, JOB, DEPTNO
        FROM EMP
        WHERE DEPTNO = 20 );
--        
SELECT * FROM VW_EMP20;

SELECT VIEW_NAME, TEXT_LENGTH, TEXT FROM USER_VIEWS;



-- 뷰 삭제

DROP VIEW VW_EMP20;



-- 인라인 뷰를 사용한 TOP-N SQL문 ( 많이 사용 )

SELECT ROWNUM, E.* FROM EMP E;  -- ROWNUM 정렬

SELECT ROWNUM, E.* FROM EMP E   -- ROWNUM, ORDER BY 정렬
    ORDER BY SAL DESC;
    
SELECT ROWNUM, E.*
    FROM ( SELECT *
            FROM EMP E
            ORDER BY SAL DESC ) E;    -- SAL 상위 순

WITH E AS ( SELECT * FROM EMP ORDER BY  SAL DESC ) -- WITH절
SELECT ROWNUM, E.*
    FROM E
    WHERE ROWNUM < 3;

SELECT ROWNUM, E.*
    FROM ( SELECT *
            FROM EMP E
            ORDER BY SAL DESC ) E;    -- SAL 상위 순
            
            
-- 시퀀스 생성

CREATE TABLE DEPT_SEQUENCE
    AS SELECT *
         FROM DEPT
         WHERE 1 <> 1;
        
SELECT * FROM DEPT;

SELECT * FROM DEPT_SEQUENCE;

CREATE SEQUENCE SEQ_DEPT_SEQUENCE
    INCREMENT BY 10
    START WITH 10
    MAXVALUE 90
    MINVALUE 0
    NOCYCLE
    CACHE 2;
    
SELECT * FROM USER_SEQUENCES;

-- 데이터 입력

INSERT INTO DEPT_SEQUENCE ( DEPTNO, DNAME, LOC )
    VALUES ( SEQ_DEPT_SEQUENCE.NEXTVAL, 'DATABASE', 'SEOUL' );
    
SELECT * FROM DEPT_SEQUENCE ORDER BY DEPTNO;


SELECT SEQ_DEPT_SEQUENCE.CURRVAL FROM DUAL;


-- 시퀀스 수정

ALTER SEQUENCE SEQ_DEPT_SEQUENCE
    INCREMENT BY 3
    MAXVALUE 99
    CYCLE;
    
-- 시퀀스 삭제

DROP SEQUENCE SEQ_DEPT_SEQUENCE;


-- 동의어 ( 객체 이름 대신 또 다른 별칭 ), SYSTEM 권한 필요

CREATE SYNONYM E
    FOR EMP;
    
SELECT * FROM E;

DROP SYNONYM E;

