CREATE TABLE TEMP(
    COL1 VARCHAR2( 20 ),
    COL2 VARCHAR2( 20 ));
    
DESC TEMP;

GRANT SELECT ON TEMP TO ORCLSTUDY;

GRANT INSERT ON TEMP TO ORCLSTUDY;

SELECT * FROM TEMP;

REVOKE SELECT, INSERT ON TEMP FROM ORCLSTUDY;