CREATE TABLE DEPT_TCL AS SELECT * FROM DEPT;

SELECT * FROM DEPT_TCL;

INSERT INTO DEPT_TCL ( DEPTNO, DNAME, LOC )
    VALUES ( 50, 'DATABASE', 'SEOUL');
    
UPDATE DEPT_TCL SET LOC = 'SEOUL' WHERE DEPTNO = 30;

DELETE FROM DEPT_TCL WHERE DEPTNO = 40;

ROLLBACK;

COMMIT;

DELETE FROM DEPT_TCL WHERE DEPTNO = 50;

SELECT * FROM DEPT_TCL;

UPDATE DEPT_TCL SET LOC = 'SEOUL' WHERE DEPTNO = 30;

UPDATE DEPT_TCL SET DNAME = 'DATABASE' WHERE DEPTNO = 30;

