-- SUB QUERY

SELECT *
    FROM EMP
    WHERE COMM > ( SELECT COMM FROM EMP WHERE ENAME = 'ALLEN');
    
SELECT *
    FROM EMP
    WHERE HIREDATE < ( SELECT HIREDATE FROM EMP WHERE ENAME = 'JONES');
    
    
SELECT * FROM EMP, DEPT;

SELECT AVG(SAL) FROM EMP;

SELECT E.EMPNO, E.ENAME, E.JOB, E.SAL, D.DEPTNO, D.DNAME, D.LOC
       FROM  EMP E, DEPT D
            WHERE E.DEPTNO = D.DEPTNO
            AND E.DEPTNO = 20
            AND E.SAL <= ( SELECT AVG( SAL ) FROM EMP );
            
            
           
-- IN 연산자
SELECT * FROM EMP
    WHERE DEPTNO IN( 10, 30 );
    
    
SELECT MAX( SAL ) FROM EMP GROUP BY DEPTNO;

SELECT * FROM EMP 
    WHERE SAL IN( SELECT MAX( SAL ) FROM EMP GROUP BY DEPTNO );
    


-- ANY 연산자
SELECT SAL FROM EMP WHERE DEPTNO = 30;


SELECT * FROM EMP
    WHERE SAL < ANY ( SELECT SAL FROM EMP WHERE DEPTNO = 30 );
    
    
-- ALL 연산자
SELECT * FROM EMP
    WHERE SAL < ALL ( SELECT SAL FROM EMP WHERE DEPTNO = 30) ;
    
SELECT SAL, ENAME FROM EMP WHERE DEPTNO = 30;


-- EXISTS 연산자
SELECT * FROM EMP WHERE DEPTNO = 10;

SELECT * FROM EMP
    WHERE HIREDATE < ALL ( SELECT HIREDATE FROM EMP WHERE DEPTNO = 10 );
    
SELECT * FROM EMP WHERE ( DEPTNO, SAL ) IN ( SELECT DEPTNO, MAX( SAL ) FROM EMP GROUP BY DEPTNO ) ;



-- 인라인 뷰

SELECT E10.EMPNO, E10.ENAME, E10.DEPTNO, D.DNAME, D.LOC
    FROM ( SELECT * FROM EMP WHERE DEPTNO = 10 ) E10,
        ( SELECT * FROM DEPT ) D
    WHERE E10.DEPTNO = D.DEPTNO;
    
    
-- WITH 절

WITH
E10 AS ( SELECT * FROM EMP WHERE DEPTNO = 10 ),
    D AS ( SELECT * FROM DEPT )
    SELECT E10.EMPNO, E10.ENAME, E10.DEPTNO, D.DNAME, D.LOC
    FROM E10, D
     WHERE E10.DEPTNO = D.DEPTNO;
     


-- 스칼라 서브 쿼리

