-- 8/ Q1
SELECT * FROM EMP, DEPT;

SELECT E.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.SAL
    FROM EMP E, DEPT D
        WHERE E.DEPTNO = D.DEPTNO AND SAL > 2000
    ORDER BY DEPTNO;
    
    
-- 8/ Q2
SELECT DEPTNO, D.DNAME,  
TRUNC ( AVG( SAL )) AS AVG_SAL, 
        MAX( SAL ) AS MAX_SAL, 
        MIN( SAL ) AS MIN_SAL,
        COUNT(*) AS CNT
        
        FROM EMP E JOIN DEPT D USING ( DEPTNO )
        GROUP BY DEPTNO, D.DNAME;
    
    
-- 8/ Q3
SELECT D.DEPTNO, D.DNAME, E.EMPNO,
        E.ENAME, JOB, SAL
    
    FROM EMP E RIGHT OUTER JOIN DEPT D ON ( E.DEPTNO = D.DEPTNO )
    
    ORDER BY D.DEPTNO, E.ENAME;