-- 제약 조건

-- 낫 널 ( NOT NULL )

DROP TABLE TABLE_NOTNULL;

CREATE TABLE TABLE_NOTNULL (
    LOGIN_ID VARCHAR( 20 ) NOT NULL, 
    LOGIN_PASSWORD VARCHAR ( 20 ) NOT NULL,
    TEL VARCHAR2( 20 ));
    
DESC TABLE_NOTNULL;

INSERT INTO TABLE_NOTNULL ( LOGIN_ID, LOGIN_PASSWORD )
    VALUES ( 'TEST_ID_01', '1234');
    
SELECT * FROM TABLE_NOTNULL;

-- 제약 조건 확인
SELECT * FROM USER_CONSTRAINTS;

-- 제약 조건 사용자 지정 이름 설정

CREATE TABLE TABLE_NOTNULL2 (
    LOGIN_ID VARCHAR( 20 ) CONSTRAINT TBLNN2_LGNID_NN NOT NULL, 
    LOGIN_PASSWORD VARCHAR ( 20 ) CONSTRAINT TBLNN2_LGNPW_NN NOT NULL,
    TEL VARCHAR2( 20 ));
    
-- 제약 조건 추가하기 ( ALTER )

ALTER TABLE TABLE_NOTNULL
MODIFY ( TEL NOT NULL );

UPDATE TABLE_NOTNULL
    SET TEL = '010-0000-0000'
    WHERE LOGIN_ID = 'TEST_ID_01';
    
SELECT * FROM TABLE_NOTNULL;
DESC TABLE_NOTNULL;

SELECT * FROM USER_CONSTRAINTS;

ALTER TABLE TABLE_NOTNULL2
MODIFY ( TEL CONSTRAINT TBLNN_TEL_NN1 NOT NULL );

-- 제약 조건 사용자 지정 이름 수정
ALTER TABLE TABLE_NOTNULL2
RENAME CONSTRAINT TBLNN_TEL_NN1 TO TBLNN2_TEL_NN;

-- 제약 조건 삭제
ALTER TABLE TABLE_NOTNULL2
DROP CONSTRAINT TBLNN2_TEL_NN;


DESC TBLNN2_TEL_NN;



-- 유니크 ( UNIQUE )

SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'TBL_UNIQUE';


CREATE TABLE TBL_UNIQUE (
    LOGIN_ID VARCHAR( 20 ) UNIQUE, 
    LOGIN_PASSWORD VARCHAR ( 20 ) NOT NULL,
    TEL VARCHAR2( 20 ));

DESC TBL_UNIQUE;

INSERT INTO TBL_UNIQUE ( LOGIN_ID, LOGIN_PASSWORD, TEL )
    VALUES ( 'TEST_ID_01', 'PWD01', '010-0000-0000');
    
INSERT INTO TBL_UNIQUE ( LOGIN_ID, LOGIN_PASSWORD, TEL )
    VALUES ( 'TEST_ID_02', 'PWD01', '010-0000-0000');
    
INSERT INTO TBL_UNIQUE ( LOGIN_ID, LOGIN_PASSWORD, TEL )
    VALUES ( 'NULL', 'PWD01', '010-0000-0000');
    
SELECT * FROM TBL_UNIQUE;


CREATE TABLE TBL_UNIQUE2 (
    LOGIN_ID VARCHAR( 20 ) CONSTRAINT TBLUNQ2_LGNID_UNQ UNIQUE, 
    LOGIN_PASSWORD VARCHAR ( 20 ) CONSTRAINT TBLUNQ2_LGNPW_NN NOT NULL,
    TEL VARCHAR2( 20 ));
    
-- 수정
ALTER TABLE TBL_UNIQUE
MODIFY( TEL UNIQUE );

SELECT * FROM TBL_UNIQUE;

ALTER TABLE TBL_UNIQUE
MODIFY( TEL UNIQUE CONSTRAINT TBLUNQ_TEL_UNQ UNIQUE );

ALTER TABLE TBL_UNIQUE2
RENAME CONSTRAINT TBLUNQ_TEL_UNQ TO TBLUNQ2_TEL_UNQ;

UPDATE TBL_UNIQUE
SET TEL = NULL;


-- 기본 키 ( PRIMARY KEY )

CREATE TABLE TBL_PK (
    LOGIN_ID VARCHAR( 20 ) PRIMARY KEY, 
    LOGIN_PASSWORD VARCHAR ( 20 ) NOT NULL,
    TEL VARCHAR2( 20 ));
    
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME LIKE 'TBL_PK%';
SELECT * FROM USER_INDEXES WHERE TABLE_NAME = 'TBL_PK';

SELECT * FROM USER_IND_COLUMNS;

CREATE TABLE TBL_PK2 (
    LOGIN_ID VARCHAR( 20 ) CONSTRAINT TBLPK2_LGNID_PK PRIMARY KEY, 
    LOGIN_PASSWORD VARCHAR ( 20 ) CONSTRAINT TBLPK2_LGNPW_NN NOT NULL,
    TEL VARCHAR2( 20 ));

DESC TBL_PK2;

DROP TABLE TBL_PK;

INSERT INTO TBL_PK ( LOGIN_ID, LOGIN_PASSWORD, TEL )
    VALUES ( 'TEST_ID_01', 'PWD01', '010-0000-0000');
    
SELECT * FROM TBL_PK;



-- FOREIGN KEY

SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME IN( 'EMP', 'DEPT' );


INSERT INTO EMP ( EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO )
    VALUES ( 9999, '홍길동', 'CLERK', 7788, TO_DATE( '2017/04/30', 'YYYY/MM/DD' ), 1200, NULL, 50);
    
SELECT * FROM DEPT;

CREATE TABLE DEPT_FK(
    DEPTNO NUMBER( 2 )CONSTRAINT DEPT_FK_PK PRIMARY KEY,
    DNAME VARCHAR2( 14 ),
    LOC VARCHAR2( 13 ));

DESC DEPT_FK;
 
    
CREATE TABLE EMP_FK (
    EMPNO       NUMBER( 4 ),
    ENAME       VARCHAR2( 10 ),
    JOB         VARCHAR2( 9 ),
    MGR         NUMBER( 4 ),
    HIREDATE    DATE,
    SAL         NUMBER( 7,2 ),
    COMM        NUMBER( 7,2 ),
    DEPTNO      NUMBER( 2 ) ,           -- CONSTRAINT EMPFK_DEPTNO_FK REFERENCES DEPT_FK (DEPTNO)
    CONSTRAINT EMPFK_EMPNO_PK PRIMARY KEY( EMPNO ),
    CONSTRAINT EMPFK_DEPTNO_FK FOREIGN KEY( DEPTNO )    
        REFERENCES DEPT_FK ( DEPTNO ));
    
SELECT * FROM EMP_FK;
DESC EMP_FK;

INSERT INTO DEPT_FK
    VALUES( 10, 'TEST_DNAME', 'TEST_LOC' );
SELECT * FROM DEPT_FK;

INSERT INTO EMP_FK
    VALUES ( 9999, 'TEST_NNAME', 'TEST_JOB', NULL, TO_DATE( '2001/01/01', 'YYYY/MM/DD' ), 3000, NULL, 10);

SELECT * FROM EMP_FK;

DELETE FROM DEPT_FK
    WHERE DEPTNO = 10;
    

-- 체크 ( CHECK )

CREATE TABLE TBL_CHECK(
    LOGIN_ID VARCHAR2( 20 ) CONSTRAINT TBLCK_LOGINID_PK PRIMARY KEY,
    LOGIN_PWD VARCHAR2( 20 ) CONSTRAINT TBLCK_LOGINPW_CK CHECK(LENGTH(LOGIN_PWD) > 3),
    TEL VARCHAR2( 20 ));
    
DESC TBL_CHECK;
    
    
-- 디폴트

CREATE TABLE TBL_DEFAULT(
    LOGIN_ID VARCHAR2( 20 ) CONSTRAINT TBLCK_LOGINID_PK PRIMARY KEY,
    LOGIN_PASSWORD VARCHAR2( 20 ) DEFAULT '1234',
    TEL VARCHAR2( 20 ));
    
DESC TBL_DEFAULT;

    INSERT INTO TBL_DEFAULT ( LOGIN_ID, TEL )
    VALUES( 10,  'TEST_LOC' );
    
SELECT * FROM TBL_DEFAULT;