SELECT * FROM EMP;
SELECT * FROM DEPT;

-- JOIN ( CROSS JOIN )

SELECT * FROM EMP E, DEPT D
    WHERE E.DEPTNO = D.DEPTNO
    ORDER BY EMPNO;

SELECT * FROM EMP, DEPT;

SELECT E.EMPNO, E.ENAME, D.DEPTNO, D.DNAME, D.LOC, SAL
    FROM EMP E, DEPT D
    WHERE E.DEPTNO = D.DEPTNO AND E.SAL <= 2500
    AND E.EMPNO <= 9999;
    
    
-- 등가 조인( 내부 조인, 단순 조인 ) '=' 사용
SELECT * FROM EMP E, SALGRADE S
    WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL;
    
    
SELECT E1.EMPNO, E1.ENAME, E1.MGR,
        E2.EMPNO AS MGR_EMPNO,
        E2.ENAME AS MGR_ENAME,
        E2.HIREDATE AS MGR_HIREDATE
    FROM EMP E1, EMP E2
WHERE E1.MGR = E2.EMPNO;

SELECT * FROM EMP;


-- 외부 조인

SELECT E1.EMPNO, E1.ENAME, E1.MGR,
        E2.EMPNO AS MGR_EMPNO,
        E2.ENAME AS MGR_ENAME,
        E2.HIREDATE AS MGR_HIREDATE
    FROM EMP E1, EMP E2
WHERE E1.MGR(+) = E2.EMPNO;



-- 표준 문법 JOIN

-- NATURAL JOIN
SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE,
    E.SAL, E.COMM, DEPTNO, D.DNAME, D.LOC
        FROM EMP E NATURAL JOIN DEPT D
            ORDER BY DEPTNO, E.EMPNO;
            
            
-- JOIN USING
SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE,
    E.SAL, E.COMM, DEP3TNO, D.DNAME, D.LOC
     FROM EMP E JOIN DEPT D USING( DEPTNO )
        WHERE SAL >= 3000
        ORDER BY DEPTNO, E.EMPNO;
        

-- JOIN ON
SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE,
    E.SAL, E.COMM, E.DEPTNO, D.DNAME, D.LOC
     FROM EMP E JOIN DEPT D ON( E.DEPTNO = D.DEPTNO )
        WHERE SAL <= 3000
        ORDER BY E.DEPTNO, EMPNO;
        
        
-- LEFT OUTER JOIN
SELECT E1.EMPNO, E1.ENAME, E1.MGR,
    E2.EMPNO AS MGR_EMPNO,
    E2.ENAME AS MGR_ENAME
        FROM EMP E1 LEFT OUTER JOIN EMP E2 ON( E1.MGR = E2.EMPNO )
        ORDER BY E1.EMPNO;

-- RIGHT OUTER JOIN
SELECT E1.EMPNO, E1.ENAME, E1.MGR,
    E2.EMPNO AS MGR_EMPNO,
    E2.ENAME AS MGR_ENAME
        FROM EMP E1 RIGHT OUTER JOIN EMP E2 ON( E1.MGR = E2.EMPNO )
        ORDER BY E1.EMPNO;
        
-- FULL OUTER JOIN
SELECT E1.EMPNO, E1.ENAME, E1.MGR,
    E2.EMPNO AS MGR_EMPNO,
    E2.ENAME AS MGR_ENAME
        FROM EMP E1 FULL OUTER JOIN EMP E2 ON( E1.MGR = E2.EMPNO )
        ORDER BY E1.EMPNO;